# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(max_length=64)),
                ('attachment', models.FileField(upload_to='/College/4thYearProject/smartboard/media/attachments')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('module_password', models.CharField(max_length=64)),
                ('lecturer_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Lecture Date')),
                ('notes_name', models.CharField(default='default', max_length=64)),
                ('notes', models.FileField(upload_to='/College/4thYearProject/smartboard/media/notes')),
                ('lecture_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='/College/4thYearProject/smartboard/media/videos')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Lecture')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='modulecode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Module'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Lecture'),
        ),
    ]
