# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(max_length=64)),
                ('attachment', models.FileField(upload_to='/media/attachments')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_code', models.CharField(max_length=64)),
                ('lecturer_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Lecture Date')),
                ('notes', models.FileField(upload_to='/media/notes')),
                ('Lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='/media/videos')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Lecture')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Lecture'),
        ),
    ]
