# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment_num',
            field=models.IntegerField(default=99, max_length=64),
        ),
        migrations.AddField(
            model_name='lecture',
            name='attachment_num',
            field=models.IntegerField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_num',
            field=models.IntegerField(default=99, max_length=64),
        ),
        migrations.AddField(
            model_name='lecture',
            name='notes_num',
            field=models.IntegerField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_num',
            field=models.IntegerField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='module',
            name='lecture_num',
            field=models.IntegerField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='notes',
            name='notes_num',
            field=models.IntegerField(default=99, max_length=64),
        ),
        migrations.AddField(
            model_name='video',
            name='video_num',
            field=models.IntegerField(default=99, max_length=64),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(upload_to='C:\\College\\4thYearProject\\smartboard\\static/attachments'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=models.FileField(upload_to='C:\\College\\4thYearProject\\smartboard\\static/notes'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='C:\\College\\4thYearProject\\smartboard\\static/video'),
        ),
    ]
