# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20160427_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='Lecture',
            new_name='lecture_name',
        ),
        migrations.AddField(
            model_name='notes',
            name='notes_name',
            field=models.CharField(default='default', max_length=64),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=models.FileField(upload_to='/College/4thYearProject/smartboard/media/notes'),
        ),
    ]
