# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20160429_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_num',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='attachment_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_num',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='notes_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='lecture_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes_num',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_num',
            field=models.IntegerField(default=99),
        ),
    ]
