# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20160429_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(upload_to='C:\\College\\4thYearProject\\smartboard\\static/attachments/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=models.FileField(upload_to='C:\\College\\4thYearProject\\smartboard\\static/notes/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='C:\\College\\4thYearProject\\smartboard\\static/video/%Y/%m/%d'),
        ),
    ]
